# Overview
# run container for card game simulations via Jupyter notebook

version: '3.7'

name: ${PROJECT_NAME}  # project name (aka stack)

services:

  # db
  # database
  # * login with:<br>
  # `docker exec -it ${CONTAINER_NAME} psql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -W`
  # * once in `psql`, quit with `\q`
  db:
    build: ./db  # build with `docker-compose build`

    container_name: ${PROJECT_NAME}-db

    restart: always

    ports:
      - "5433:${POSTGRES_PORT}"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    volumes:
      - ./db/data:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - cgs

  # jupyter notebook
  # also using this for running app
  notebook:
    build: ./app  # build with `docker-compose up -d --build` (build and run) or `docker-compose build` (just build)

    container_name: ${PROJECT_NAME}-notebook

    restart: always

    ports:
      - "${PORT_APP}:8888"
    
    volumes:
      - ./app/working:/home/jovyan/work  # dev
      - ./app/logs:/home/jovyan/app/logs  # prod logs

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    networks:
      - cgs

networks:
  cgs: